# 📰 News Topic Classifier Using BERT

## Problem Statement
Classify news articles into different topic categories using a pre-trained BERT transformer model.

## Objective
- Fine-tune BERT model on AG News dataset
- Classify news into 4 categories: World, Sports, Business, Sci/Tech
- Evaluate model accuracy and F1-score
- Deploy as an interactive application

## Dataset
- **AG News Dataset** - 120,000 news articles
- **Classes**: World, Sports, Business, Science/Technology
- **Features**: Article Title + Description

In [1]:
!pip install pandas
!pip install evaluate accelerate
!pip install numpy

Requirement already satisfied: pandas in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\aliim\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

Requirement already satisfied: evaluate in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.4.6)
Requirement already satisfied: accelerate in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.13.0)
Requirement already satisfied: datasets>=2.0.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from evaluate) (4.8.5)
Requirement already satisfied: numpy>=1.17 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from evaluate) (2.4.3)
Requirement already satisfied: dill in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from evaluate) (0.4.1)
Requirement already satisfied: pandas in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from evaluate) (3.0.1)
Requirement already satisfied: requests>=2.19.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from evaluate) (2.32.5)
Requirement already satisfied: tqdm>=4.62.1 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from evaluate) (3.7.0)
Requirement already satisfied: multiprocess in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from evaluate) (0.70.19)
Requirement already satisfied: fsspec>=2021.05.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from fsspec[http]>=2021.05.0->evaluate) (2026.2.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from evaluate) (1.7.1)
Requirement already satisfied: packaging in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from evaluate) (26.0)
Requirement already satisfied: psutil in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from accelerate) (7.2.2)
Requirement already satisfied: pyyaml in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from accelerate) (2.11.0)
Requirement already satisfied: safetensors>=0.4.3 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from datasets>=2.0.0->evaluate) (3.25.2)
Requirement already satisfied: pyarrow>=21.0.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from datasets>=2.0.0->evaluate) (24.0.0)
Requirement already satisfied: httpx<1.0.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from datasets>=2.0.0->evaluate) (0.28.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.5)
Requirement already satisfied: anyio in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (4.12.1)
Requirement already satisfied: certifi in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (2026.2.25)
Requirement already satisfied: httpcore==1.* in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (1.0.9)
Requirement already satisfied: idna in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (3.11)
Requirement already satisfied: h11>=0.16 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.0.0->evaluate) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.2)
Requirement already satisfied: typer in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.19.0->evaluate) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.19.0->evaluate) (2.6.3)
Requirement already satisfied: setuptools<82 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from torch>=2.0.0->accelerate) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: colorama in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tqdm>=4.62.1->evaluate) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.2.1 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (0.1.2)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\aliim\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.4.3)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\aliim\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
import kagglehub
import os

print("Downloading AG News dataset...")
download_path = kagglehub.dataset_download("amananandrai/ag-news-classification-dataset")
file_path = os.path.join(download_path, "train.csv")

df = pd.read_csv(
    file_path, 
    names=["Class Index", "Title", "Description"], 
    encoding="utf-8",
    engine="python",
    on_bad_lines="warn"
)

df = df.sample(n=20000, random_state=42)

print(f" Loaded {len(df)} articles\n")

print("Dataset Info:")
print(f"  - Shape: {df.shape}")
print(f"  - Columns: {df.columns.tolist()}")
print("\nFirst 3 rows:")
print(df.head(3))

C:\Users\aliim\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading AG News dataset...
 Loaded 20000 articles

Dataset Info:
  - Shape: (20000, 3)
  - Columns: ['Class Index', 'Title', 'Description']

First 3 rows:
      Class Index                                              Title  \
71788           3       BBC set for major shake-up, claims newspaper
67218           4                       Taking Microsoft for a spin?
54066           3  September sales at Target stores beat retail a...

                                             Description
71788  London - The British Broadcasting Corporation,...
67218  The software juggernaut that conquered the des...
54066  MINNEAPOLIS - While other retailers struggled ...

In [4]:
from transformers import AutoTokenizer

model_ckpt = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [5]:
import pandas as pd
from datasets import Dataset

df['Class Index'] = pd.to_numeric(df['Class Index'], errors='coerce')

df = df.dropna(subset=['Class Index'])

df['labels'] = df['Class Index'].astype(int) - 1

df['text'] = df['Title'].astype(str) + " " + df['Description'].astype(str)

hf_dataset = Dataset.from_pandas(df[['text', 'labels']])

def tokenize_batch(batch):
    return tokenizer(
        batch["text"], 
        padding="max_length", 
        truncation=True, 
        max_length=128
    )

dataset_tokenized = hf_dataset.map(tokenize_batch, batched=True)
dataset_tokenized.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

print(f"Cleaned! Remaining rows: {len(df)}")

Map: 100%|██████████████████████████████████████████████████████████████| 19999/19999 [00:04<00:00, 4431.18 examples/s]

Cleaned! Remaining rows: 19999

In [6]:
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer
import evaluate
import numpy as np

In [7]:
model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased", 
    num_labels=4
)

Loading weights: 100%|█████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 2692.13it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [8]:
accuracy_metric = evaluate.load("accuracy")
f1_metric = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    
    acc = accuracy_metric.compute(predictions=predictions, references=labels)
    f1 = f1_metric.compute(predictions=predictions, references=labels, average="weighted")
    
    return {**acc, **f1}

In [9]:

training_args = TrainingArguments(
    output_dir="./bert_news_model",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    TENSORBOARD_LOGGING_DIR='./logs',
)

[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

In [10]:

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_tokenized, # Using your tokenized dataset from Task 1
    eval_dataset=dataset_tokenized.select(range(500)), # Small subset for quick eval
    compute_metrics=compute_metrics,
)

In [11]:


trainer.train()

C:\Users\aliim\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\torch\utils\data\dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.56it/s]
C:\Users\aliim\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\torch\utils\data\dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.57it/s]
C:\Users\aliim\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\torch\utils\data\dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.31it/s]
[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=3750, training_loss=0.1918805160522461, metrics={'train_runtime': 20711.3072, 'train_samples_per_second': 2.897, 'train_steps_per_second': 0.181, 'total_flos': 3946539364604928.0, 'train_loss': 0.1918805160522461, 'epoch': 3.0})

In [13]:
model_path = "./final_bert_news_model"

trainer.save_model(model_path)
tokenizer.save_pretrained(model_path)

print(f"Model saved successfully to {model_path}!")

Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.18it/s]

Model saved successfully to ./final_bert_news_model!

In [14]:
eval_results = trainer.evaluate()

print(f"--- Evaluation Results ---")
print(f"Accuracy: {eval_results['eval_accuracy']:.4f}")
print(f"F1 Score:  {eval_results['eval_f1']:.4f}")
print(f"Loss:      {eval_results['eval_loss']:.4f}")

C:\Users\aliim\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\torch\utils\data\dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

--- Evaluation Results ---
Accuracy: 0.9820
F1 Score:  0.9819
Loss:      0.0940

In [15]:
output_dir = "./saved_bert_news_model"

model.save_pretrained(output_dir)

tokenizer.save_pretrained(output_dir)

print(f"Project state saved to {output_dir}")

Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.13it/s]

Project state saved to ./saved_bert_news_model